import React from 'react'
import Nav from './Nav'
import Footer from './Footer'

function TermsConditions() {
    return (
        <>
        <Nav/>
            {/* <!-- Banner Area Start --> */}
            <div className="banner-area-wrapper">
                <div className="banner-area text-center">
                    <div className="container">
                        <div className="row">
                            <div className="col-12">
                                <div className="banner-content-wrapper">
                                    <div className="banner-content">
                                        <h2>Terms & Conditions</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {/* /* // <!-- Banner Area End --> */}

            <div className="terms ptb-50">
                <div className="container">
                    <div className="row Text-center">
                        <h1 className='text-center pb-20'>PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY!</h1>
                        <div className="col-sm-12 col-md-12 col-lg-12">
             
                            <p>Welcome to  These Terms of Use describe the terms and conditions applicable to your access and use of the websites at .&nbsp; This document is a legally binding agreement between you as the user(s) of the Sites (referred to as &ldquo;you&rdquo;, &ldquo;your&rdquo; or &ldquo;User&rdquo; hereinafter) and the  entity listed in clause 2.1 below (referred to as &ldquo;we&rdquo;, &ldquo;our&rdquo; or &ldquo;&rdquo; hereinafter).</p>
                            <h2 id="application_acceptance">1. Application and Acceptance of the Terms</h2>
                            <p>1.1 Your use of the Sites and &rsquo;s services, software and products (collectively referred to&nbsp;as the &ldquo;Services&rdquo; hereinafter) is subject to the terms and conditions contained in this document as well as the Privacy Policy, the Product Listing Policy and any other rules and policies of the Sites that  may publish from time to time. This document and such other rules and policies of the Sites are collectively referred to below as the &ldquo;Terms&rdquo;. By accessing the Sites or using the Services, you agree to accept and be bound by the Terms.&nbsp; Please do not use the Services or the Sites if you do not accept all of the Terms.&nbsp;</p>
                            <p>1.2 You may not use the Services and may not accept the Terms if (a) you are not of legal age to form a binding contract with , or (b) you are not permitted to receive any Services under the laws of the US.</p>
                            <p>1.3 You acknowledge and agree that  may amend any Terms at any time by posting the relevant amended and restated Terms on the Sites.&nbsp; By continuing to use the Services or the Sites, you agree that the amended Terms will apply to you.</p>
                            <p>1.4 If  has posted or provided a translation of the English language version of the Terms, you agree that the translation is provided for convenience only and that the English language version will govern your uses of the Services or the Sites.</p>
                            <p>1.5 You may be required to enter into a separate agreement, whether online or offline, with  or our affiliate for any Service (&ldquo;Additional Agreements&rdquo;).&nbsp; If there is any conflict or inconsistency between the Terms and an Additional Agreement, the Additional Agreement shall take precedence over the Terms only in relation to that Service concerned.&nbsp; &nbsp;</p>
                            <p>1.6 The Terms may not otherwise be modified except in writing by an authorized officer of .</p>
                            <h2 id="provision_services">2. Provision of Services</h2>
                            <p>2.1 Under California jurisdiction, the  contracting entity that you are contracting with is .</p>
                            <p>2.2 You must register as a member on the Sites in order to access and use some Services. Further,  reserves the right, without prior notice, to restrict access to or use of certain Services (or any features within the Services) to paying Users or subject to other conditions that  may impose in our discretion.</p>
                            <p>2.3 Services (or any features within the Services) may vary for different regions and countries. No warranty or representation is given that a particular Service or feature or function thereof or the same type and extent of the Service or features and functions thereof will be available for Users.  may in our sole discretion limit, deny or create different level of access to and use of any Services (or any features within the Services) with respect to different Users.</p>
                            <p>2.4  may launch, change, upgrade, impose conditions to, suspend, or stop any Services (or any features within the Services) without prior notice except that in case of a fee-based Service, such changes will not substantially adversely affect the paying Users in enjoying that Service.</p>
                            <p>2.5 Some Services may be provided by &rsquo;s affiliates on behalf of .</p>
                            <h2 id="users_generally">3. Users Generally</h2>
                            <p>3.1 As a condition of your access to and use of the Sites or Services, you agree that you will comply with all applicable laws and regulations when using the Sites or Services.</p>
                            <p>3.2 You agree to use the Sites or Services solely for your own private and internal purposes. You agree that (a) you will not copy, reproduce, download, re-publish, sell, distribute or resell any Services or any information, text, images, graphics, video clips, sound, directories, files, databases or listings, etc available on or through the Sites (the &ldquo;Site Content&rdquo;), and (b) you will not copy, reproduce, download, compile or otherwise use any Site Content for the purposes of operating a business that competes with , or otherwise commercially exploiting the Site Content. Systematic retrieval of Site Content from the Sites to create or compile, directly or indirectly, a collection, compilation, database or directory (whether through robots, spiders, automatic devices or manual processes) without written permission from  is prohibited. Use of any content or materials on the Sites for any purpose not expressly permitted in the Terms is prohibited.</p>
                            <p>3.3 You must read &rsquo;s Privacy Policy which governs the protection and use of personal information about Users in the possession of  and our affiliates. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy.</p>
                            <p>3.4  may allow Users to access to content, products or services offered by third parties through hyperlinks (in the form of word link, banners, channels or otherwise), API or otherwise to such third parties' web sites. You are cautioned to read such web sites' terms and conditions and/or privacy policies before using the Sites. You acknowledge that  has no control over such third parties' web sites, does not monitor such web sites, and shall not be responsible or liable to anyone for such web sites, or any content, products or services made available on such web sites.</p>
                            <p>3.5 You agree not to undertake any action to undermine the integrity of the computer systems or networks of  and/or any other User nor to gain unauthorized access to such computer systems or networks.</p>
                            <p>3.6 You agree not to undertake any action which may undermine the integrity of &rsquo;s feedback system, such as leaving positive feedback for yourself using secondary Member IDs or through third parties or by leaving unsubstantiated negative feedback for another User.</p>
                            <p>3.7 By posting or displaying any information, content or material (&ldquo;User Content&rdquo;) on the Sites or providing any User Content to  or our representative(s), you grant an irrevocable, perpetual, worldwide, royalty-free, and sub-licensable (through multiple tiers) license to  to display, transmit, distribute, reproduce, publish, duplicate, adapt, modify, translate, create derivative works, and otherwise use any or all of the User Content in any form, media, or technology now known or not currently known in any manner and for any purpose which may be beneficial to the operation of the Sites, the provision of any Services and/or the business of the User. You confirm and warrant to  that you have all the rights, power and authority necessary to grant the above license.</p>
                            <h2 id="member_accounts">4. Member Accounts</h2>
                            <p>4.1 User must be registered on the Sites to access or use some Services (a registered User is also referred to as a &ldquo;Member&rdquo; below). Except with &rsquo;s approval, one User may only register one member account on the Sites.  may cancel or terminate a User&rsquo;s member account if  has reasons to suspect that the User has concurrently registered or controlled two or more member accounts. Further,  may reject User&rsquo;s application for registration for any reason.</p>
                            <p>4.2 Upon registration on the Sites,  shall assign an account and issue a member ID and password (the latter shall be chosen by a registered User during registration) to each registered User. An account may have a web-based email account with limited storage space for the Member to send or receive emails.</p>
                            <p>4.3 A set of Member ID and password is unique to a single account. Each Member shall be solely responsible for maintaining the confidentiality and security of your Member ID and password and for all activities that occur under your account. No Member may share, assign, or permit the use of your Member account, ID or password by another person outside of the Member&rsquo;s own business entity. Member agrees to notify  immediately if you become aware of any unauthorized use of your password or your account or any other breach of security of your account.</p>
                            <p>4.4 Member agrees that all activities that occur under your account (including without limitation, posting any company or product information, clicking to accept any Additional Agreements or rules, subscribing to or making any payment for any services, sending emails using the email account or sending SMS) will be deemed to have been authorized by the Member.</p>
                            <p>4.5 Member acknowledges that sharing of your account with other persons, or allowing multiple users outside of your business entity to use your account (collectively, "multiple use"), may cause irreparable harm to  or other Users of the Sites. Member shall indemnify , our affiliates, directors, employees, agents and representatives against any loss or damages (including but not limited to loss of profits) suffered as a result of the multiple use of your account. Member also agrees that in case of the multiple use of your account or Member&rsquo;s failure to maintain the security of your account,  shall not be liable for any loss or damages arising from such a breach and shall have the right to suspend or terminate Member&rsquo;s account without liability to Member.</p>
                            <p>4.6 If a user account has not been activated on Export Portal for 90 calendar days, the account will be restricted and eventually blocked.</p>
                            <h2 id="members_responsibilities">5. Member&rsquo;s Responsibilities</h2>
                            <p>5.1 Each Member represents, warrants and agrees that (a) you have full power and authority to accept the Terms, to grant the license and authorization and to perform the obligations hereunder; (b) you use the Sites and Services for business purposes only; and (c) the address you provide when registering is the principal place of business of your business entity. &nbsp;For purposes of this provision, a branch or liaison office will not be considered a separate entity and your principal place of business will be deemed to be that of your head office.</p>
                            <p>5.2 Member will be required to provide information or material about your entity, business or products/services as part of the registration process on the Sites or your use of any Service or the member account.&nbsp; Each Member represents, warrants and agrees that (a) such information and material whether submitted during the registration process or thereafter throughout the continuation of the use of the Sites or Service is true, accurate, current and complete, and (b) you will maintain and promptly amend all information and material to keep it true, accurate, current and complete.</p>
                            <p>5.3 Upon becoming a Member, you consent to the inclusion of the contact information about you in our Buyer Database and authorize  and our affiliates to share the contact information with other Users or otherwise use your personal information in accordance with the Privacy Policy.</p>
                            <p>5.4 Each Member represents, warrants and agrees that (a) you shall be solely responsible for obtaining all necessary third party licenses and permissions regarding any User Content that you submit, post or display; (b) any User Content that you submit, post or display does not infringe or violate any of the copyright, patent, trademark, trade name, trade secrets or any other personal or proprietary rights of any third party (&ldquo;Third Party Rights&rdquo;); (c) you have the right and authority to sell, trade, distribute or export or offer to sell, trade, distribute or export the products or services described in the User Content and such sale, trade, distribution or export or offer does not violate any Third Party Rights and (d) you and your affiliates are not the subject of any trade restrictions, sanctions or other legal restrictions enacted by any country, international organization or jurisdiction.</p>
                            <p>5.5 Each Member further represents, warrants and agrees that the User Content that you submit, post or display shall:</p>
                            <p>a. be true, accurate, complete and lawful;</p>
                            <p>b. not be false, misleading or deceptive;</p>
                            <p>c. not contain information that is defamatory, libelous, threatening or harassing, obscene, objectionable, offensive, sexually explicit or harmful to minors;</p>
                            <p>d. not contain information that is discriminatory or promotes discrimination based on race, sex, religion, nationality, disability, sexual orientation or age;</p>
                            <p>e. not violate the Product Listing Policy, other Terms or any applicable Additional Agreements</p>
                            <p>f. not violate any applicable laws and regulations (including without limitation those governing export control, consumer protection, unfair competition, or false advertising) or promote any activities which may violate any applicable laws and regulations;</p>
                            <p>g. not contain any link directly or indirectly to any other web Sites which includes any content that may violate the Terms.</p>
                            <p>5.6 Each Member further represents, warrants and agrees that you shall:</p>
                            <p>a. carry on your activities on the Sites in compliance with any applicable laws and regulations;</p>
                            <p>b. conduct your business transactions with other users of the Sites in good faith;</p>
                            <p>c. carry on your activities in accordance with the Terms and any applicable Additional Agreements;</p>
                            <p>d. not use the Services or Sites to defraud any person or entity (including without limitation sale of stolen items, use of stolen credit/debit cards);</p>
                            <p>e. not impersonate any person or entity, misrepresent yourself or your affiliation with any person or entity;</p>
                            <p>f. not engage in spamming or phishing;</p>
                            <p>g. not engage in any other unlawful activities (including without limitation those which would constitute a criminal offense, give rise to civil liability,&nbsp; etc) or encourage or abet any unlawful activities;</p>
                            <p>h. not involve attempts to copy, reproduce, exploit or expropriate &rsquo;s various proprietary directories, databases and listings;</p>
                            <p>i. not involve any computer viruses or other destructive devices and codes that have the effect of damaging, interfering with, intercepting or expropriating any software or hardware system, data or personal information;</p>
                            <p>j. not involve any scheme to undermine the integrity of the data, systems or networks used by  and/or any user of the Sites or gain unauthorized access to such data, systems or networks;</p>
                            <p>k. not engage in any activities that would otherwise create any liability for  or our affiliates. &nbsp;</p>
                            <p>5.7 Member may not use the Services and member account to engage in activities which are identical or similar to &rsquo;s e-commerce marketplace business.</p>
                            <p>5.8 If Member provides a business referee, Member represents, warrants and agrees that you have obtained all necessary consents, approvals and waivers from your business partners and associates to (a) act as your business referee; (b) post and publish their contact details and information, reference letters and comments on their behalf; and (c) that third parties may contact such business referees to support claims or statements made about you. You further warrant and agree that all reference letters and comments are true and accurate and third parties may contact the business referees without the need to obtain your consent.</p>
                            <p>5.9 Member agrees to provide all necessary information, materials and approval, and render all reasonable assistance and cooperation necessary for &rsquo;s provision of the Services, evaluating whether Member has breached the Terms and/or handling any complaint against the Member.&nbsp; If Member&rsquo;s failure to do so results in delay in, or suspension or termination of, the provision of any Service,  shall not be obliged to extend the relevant service period nor shall be liable for any loss or damages arising from such delay, suspension or termination.</p>
                            <p>5.10 Member acknowledges and agrees that  shall not be required to actively monitor nor exercise any editorial control whatsoever over the content of any message or material or information created, obtained or accessible through the Services or Sites.  does not endorse, verify or otherwise certify the contents of any comments or other material or information made by any Member. Each Member is solely responsible for the contents of their communications and may be held legally liable or accountable for the content of their comments or other material or information</p>
                            <p>5.11 Member acknowledges and agrees that the Services may only be used by businesses and their representatives for business use and not for individual consumers or for personal use.</p>
                            <p>5.12 Member acknowledges and agrees that each Member is solely responsible for observing applicable laws and regulations in its respective jurisdictions to ensure that all use of the Site and Services are in compliance with the same.</p>
                            <p>5.13 Users acknowledge that when a user creates draft items, they will be removed within 10 days if not published. After 10 days, Export Portal automatically deletes them from the system.</p>
                            <p>5.14 Each Member represents, warrants, and agrees to respect and completely adhere to Export Portal's Chat terms and conditions, which are based on security, honesty, and legality.</p>
                            <p>5.14.1 While using Export Portal&rsquo;s Chat option, you can:</p>
                            <p>a. create, access, view, and answer messages from other users coming into your chat window and freely communicate about export and import issues, international transactions, order details, product variations, shipping fees, and other unexpected issues and questions to save time and make the purchasing process faster;</p>
                            <p>b. chat in real-time with users, using an intelligent and secure communication and collaboration tool, which is specifically designed for users who want to trade on the spot with minimal time investment;</p>
                            <p>c. establish new partnerships with other users within Export Portal&rsquo;s website frames;</p>
                            <p>d. send an offer to different recipients;</p>
                            <p>e. keep the most important information in one location and be sure this information is securely stored in your chats' history without risks of being shared or stolen from third parties.&nbsp;&nbsp;</p>
                            <p>5.14.2 While using Export Portal&rsquo;s Chat option, you agree not to:</p>
                            <p>a. share any personal information, including personal contact details (phone numbers, email addresses, etc.) as well as private data such as bank account data, personal ID number, copies of documents, and other important information for the sake of your personal security;&nbsp;</p>
                            <p>b. discuss and/or organize any kind of fraudulent schemes which may negatively affect other website users and their business;&nbsp;</p>
                            <p>c. establish deals and arrangements which will take place outside of Export Portal&rsquo;s website as this can undermine the security of your transactions, products, and finances;&nbsp;</p>
                            <p>d. share promo materials and ads (direct and hidden) in regards to other eCommerce websites where the transaction is possible without Export Portal being involved, as this can undermine the security of your transactions, products, and finances;&nbsp;</p>
                            <p>e. offer and organize transaction offers outside of Export Portal&rsquo;s website as this can jeopardize the security of your transactions, products, and finances, and you won't be able to open disputes or get your money back if there are any problems;</p>
                            <p>f. use profanity or disrespectful language as well as different suspecious advertisments and images;</p>
                            <p>g. badmouth Export Portal&rsquo;s website and any Export Portal-related feature or functionality. Any issue in regards to our website functionality can be immediately addressed to our Support team and solved right on the spot;</p>
                            <p>h. offer fraudulent finance schemes which may lead to other users' security being at risk.</p>
                            <p>In case any activity which could have a negative impact on Export Portal and its users is detected by our smart system, a warning email message will be sent to your inbox. In the event that you continue breaking Export Portal chat&rsquo;s norms, you may be fully blocked and removed from our website.</p>
                            <p>Export Portal takes security extremely seriously, and any user who violates our terms and conditions may be blocked and permanently barred from using the platform. If we are required to work with law enforcement agencies, we will do so.</p>
                            <h2 id="breaches_members">6. Breaches by Members</h2>
                            <p>6.1  reserves the right in our sole discretion to remove, modify or reject any User Content that you submit to, post or display on the Sites which we reasonably believe is unlawful, violates the Terms, could subject &nbsp;or our affiliates to liability, or is otherwise found inappropriate in &rsquo;s opinion.</p>
                            <p>6.2 If any Member breaches any Terms or if  has reasonable grounds to believe that any Member is in breach of any the Terms,  shall have the right to impose a penalty against the Member, or suspend or terminate the Member&rsquo;s account or subscription of any Service without any liability to the Member.&nbsp; &nbsp; shall also have the right to restrict, refuse or ban any and all current or future use of any other Service that may be provided by .&nbsp; The penalties that  may impose include, among others, warning, removing any product listing or other User Content that the Member has submitted, posted or displayed, imposing restrictions on the number of product listings that the Member may post or display, or imposing restrictions on the Member&rsquo;s use of any features or functions of any Service for such period as  may consider appropriate in our sole discretion.</p>
                            <p>6.3 Without limiting the generality of the provisions of the Terms, a Member would be considered as being in breach of the Terms in any of the following circumstances:</p>
                            <p>a. upon complaint or claim from any third party,  has reasonable grounds to believe that such Member has willfully or materially failed to perform your contract with such third party including without limitation where the Member has failed to deliver any items ordered by such third party after receipt of the purchase price, or where the items Member has delivered materially fail to meet the terms and descriptions outlined in your contract with such third party.</p>
                            <p>b.  has reasonable grounds to suspect that such Member has used a stolen credit card or other false or misleading information in any transaction with a counter party,</p>
                            <p>c.  has reasonable grounds to suspect that any information provided by the Member is not current or complete or is untrue, inaccurate, or misleading, or</p>
                            <p>d.  believes that the Member&rsquo;s actions may cause financial loss or legal liability to  or our affiliates or any other Users.</p>
                            <p>6.4  reserves the right to cooperate fully with governmental authorities, private investigators and/or injured third parties in the investigation of any suspected criminal or civil wrongdoing. &nbsp;Further,  may disclose the Member's identity and contact information, if requested by a government or law enforcement body, an injured third party, or as a result of a subpoena or other legal action.&nbsp;  shall not be liable for damages or results arising from such disclosure, and Member agrees not to bring any action or claim against  for such disclosure.</p>
                            <p>6.5 If a Member is in breach of the Terms,  also reserves the right to publish the records of such breach on the Sites.&nbsp; If such breach involves or is reasonably suspected of involving dishonest or fraudulent activities,  also reserves the right to disclose the records of such breach to our affiliates. Such  affiliates may impose limitation on, suspend or terminate the Member&rsquo;s use of all or part of the services provided by such affiliates to the Member, take other remedial actions, and publish the records about the Member&rsquo;s breach of the Terms on the websites operated by or controlled by such  affiliates.</p>
                            <p>6.6  may, at any time and in our reasonable discretion, impose limitations on, suspend or terminate the Member&rsquo;s use of any Service or the Sites without being liable to the Member if  has received notice that the Member is in breach of any agreement or undertaking with any affiliate of  and such breach involves or is reasonably suspected of involving dishonest or fraudulent activities.&nbsp;  shall have the right to publish the records of such breach on the Sites.&nbsp;  shall not be required to investigate such breach or request confirmation from the Member.</p>
                            <p>6.7 Each Member agrees to indemnify , our affiliates, directors, employees, agents and representatives and to hold them harmless, from any and all damages, losses, claims and liabilities (including legal costs on a full indemnity basis) which may arise from your submission, posting or display of any User Content, from your use of the Sites or Services, or from your breach of the Terms.</p>
                            <p>6.8 Each Member further agrees that  is not responsible, and shall have no liability to you or anyone else for any User Content or other material transmitted over the Sites, including fraudulent, untrue, misleading, inaccurate, defamatory, offensive or illicit material and that the risk of damage from such material rests entirely with each Member.  reserves the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by the Member, in which event the Member shall cooperate with  in asserting any available defenses.</p>

                        </div>
                    </div>
                </div>
            </div>
            <Footer/>
        </>





    )
}

export default TermsConditions  